=== oasis-tcs/csaf/csaf_2.1/json_schema/extension-metaschema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://docs.oasis-open.org/csaf/csaf/v2.1/schema/extension-metaschema.json",
  "title": "CSAF Extension Metaschema",
  "description": "Representation of a CSAF Extension Schema",
  "$vocabulary": {
    "https://json-schema.org/draft/2020-12/vocab/core": true,
    "https://json-schema.org/draft/2020-12/vocab/applicator": true,
    "https://json-schema.org/draft/2020-12/vocab/unevaluated": true,
    "https://json-schema.org/draft/2020-12/vocab/validation": true,
    "https://json-schema.org/draft/2020-12/vocab/meta-data": true,
    "https://json-schema.org/draft/2020-12/vocab/format-assertion": true,
    "https://json-schema.org/draft/2020-12/vocab/content": true
  },
  "$defs": {
    "content_schema_t": {
      "title": "CSAF Extension Content $schema Type",
      "description": "Contains the actual value of the $schema property.",
      "type": "string",
      "format": "uri",
      "pattern": "^(?!https:\\/\\/docs\\.oasis-open\\.org\\/csaf\\/csaf\\/v2\\.1\\/([^\\/\\s]+\/)*schema\\/extension-content\\.json)(https:\\/\\/[a-z0-9](([a-z0-9-]){0,61}[a-z0-9])?(\\.[a-z0-9](([a-z0-9-]){0,61}[a-z0-9])?)+\\/([^\\/\\s]+\/)*[^\\/\\s]+_(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?\\.json)$"
    },
    "schema": {
      "$dynamicAnchor": "meta",
      "allOf": [
        { "$ref": "https://json-schema.org/draft/2020-12/meta/core" },
        { "$ref": "https://json-schema.org/draft/2020-12/meta/applicator" },
        { "$ref": "https://json-schema.org/draft/2020-12/meta/unevaluated" },
        { "$ref": "https://json-schema.org/draft/2020-12/meta/validation" },
        { "$ref": "https://json-schema.org/draft/2020-12/meta/meta-data" },
        { "$ref": "https://json-schema.org/draft/2020-12/meta/format-assertion" }
      ]
    }
  },
  "type": "object",
  "required": [
    "$schema",
    "$id",
    "title",
    "description",
    "type",
    "required",
    "properties",
    "additionalProperties"
  ],
  "properties": {
    "$schema": {
      "title": "CSAF Extension Metaschema",
      "description": "Contains the URL of the CSAF Extension Metaschema JSON schema which the JSON schema promises to be valid for.",
      "type": "string",
      "const": "https://docs.oasis-open.org/csaf/csaf/v2.1/schema/extension-metaschema.json"
    },
    "$id": {
      "title": "CSAF Extension Schema ID",
      "description": "Contains the ID as URL of the CSAF Extension JSON schema which identifies the CSAF Extension Schema.",
      "$ref": "#/$defs/content_schema_t"
    },
    "title": {
      "title": "Title of the CSAF Extension",
      "description": "Contains the title for the CSAF Extension Schema.",
      "type": "string",
      "minLength": 1
    },
    "description": {
      "title": "Description of the CSAF Extension",
      "description": "Contains the description for the CSAF Extension Schema detailing what the CSAF Extension is about.",
      "type": "string",
      "minLength": 1
    },
    "type": {
      "title": "Type of CSAF Extension Schema",
      "description": "Contains the type of the CSAF Extension Schema which is always `object`.",
      "type": "string",
      "const": "object"
    },
    "$defs": {
      "title": "CSAF Extension Schema Definitions",
      "description": "Contains the definitions as object of the CSAF Extension Schema.",
      "$ref": "#/$defs/schema",
      "minProperties": 1
    },
    "required": {
      "title": "CSAF Extension Schema Required Properties",
      "description": "Contains the list of required properties.",
      "type": "array",
      "const": [
        "$schema",
        "category",
        "critical",
        "content"
      ]
    },
    "properties": {
      "title": "CSAF Extension Schema Properties",
      "description": "Contains the definition of the properties a CSAF Extension Schema needs.",
      "type": "object",
      "required": [
        "$schema",
        "category",
        "critical",
        "content"
      ],
      "properties": {
        "$schema": {
          "title": "CSAF Extension Schema",
          "description": "Contains the definition of the object of the CSAF Extension JSON schema which the JSON object promises to be valid for.",
          "type": "object",
          "maxProperties": 5,
          "minProperties": 5,
          "required": [
            "title",
            "description",
            "type",
            "format"
          ],
          "properties": {
            "title": {
              "title": "Title of the CSAF Extension $schema value",
              "description": "Contains the title for the CSAF Extension $schema.",
              "type": "string",
              "default": "CSAF Extension Schema",
              "minLength": 1
            },
            "description": {
              "title": "Description of the CSAF Extension $schema value",
              "description": "Contains the description for the CSAF Extension $schema value.",
              "type": "string",
              "default": "Contains the URL of the CSAF Extension JSON schema which the JSON object promises to be valid for.",
              "minLength": 1
            },
            "type": {
              "title": "Type of the CSAF Extension $schema value",
              "description": "Contains the type of the $schema value which is `string`.",
              "type": "string",
              "const": "string"
            },
            "format": {
              "title": "Format of the CSAF Extension $schema value",
              "description": "Contains the format of the $schema value which is `uri`.",
              "type": "string",
              "const": "uri"
            },
            "const": {
              "title": "CSAF Extension $schema value",
              "description": "Contains the actual value of the $schema property.",
              "$ref": "#/$defs/content_schema_t"
            },
            "pattern": {
              "title": "CSAF Extension $schema pattern",
              "description": "Contains the pattern for value of the $schema property.",
              "type": "string",
              "const": "^(?!https:\\/\\/docs\\.oasis-open\\.org\\/csaf\\/csaf\\/v2\\.1\\/([^\\/\\s]+\/)*schema\\/extension-content\\.json)(https:\\/\\/[a-z0-9](([a-z0-9-]){0,61}[a-z0-9])?(\\.[a-z0-9](([a-z0-9-]){0,61}[a-z0-9])?)+\\/([^\\/\\s]+\/)*[^\\/\\s]+_(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?\\.json)$"
            }
          },
          "additionalProperties": false
        },
        "category": {
          "title": "CSAF Extension Category",
          "description": "Contains the definition of the object of the CSAF Extension Category.",
          "type": "object",
          "required": [
            "title",
            "description",
            "type",
            "enum"
          ],
          "properties": {
            "title": {
              "title": "Title of the CSAF Extension Category value",
              "description": "Contains the title for the CSAF Extension category.",
              "type": "string",
              "default": "Extension Category",
              "minLength": 1
            },
            "description": {
              "title": "Description of the CSAF Extension Category value",
              "description": "Contains the description for the CSAF Extension category value.",
              "type": "string",
              "default": "Holds the category of the extension content.",
              "minLength": 1
            },
            "type": {
              "title": "Type of the CSAF Extension Category value",
              "description": "Contains the type of the category value which is `string`.",
              "type": "string",
              "const": "string"
            },
            "enum": {
              "title": "Options of the CSAF Extension Category value",
              "description": "Contains the possible options for the category.",
              "type": "array",
              "maxItems": 3,
              "minItems": 1,
              "uniqueItems": true,
              "items": {
                "type": "string",
                "enum": [
                  "essential",
                  "significant",
                  "supplementary"
                ]
              }
            }
          },
          "additionalProperties": false
        },
        "critical": {
          "title": "CSAF Extension Critical",
          "description": "Contains the definition of the object of the CSAF Extension critical.",
          "type": "object",
          "maxProperties": 5,
          "required": [
            "title",
            "description",
            "type"
          ],
          "properties": {
            "title": {
              "title": "Title of the CSAF Extension Critical value",
              "description": "Contains the title for the CSAF Extension critical.",
              "type": "string",
              "default": "Critical",
              "minLength": 1
            },
            "description": {
              "title": "Description of the CSAF Extension Critical value",
              "description": "Contains the description for the CSAF Extension critical value.",
              "type": "string",
              "default": "Determines whether using the extension would fail a mandatory test.",
              "minLength": 1
            },
            "type": {
              "title": "Type of the CSAF Extension Critical value",
              "description": "Contains the type of the critical value which is `boolean`.",
              "type": "string",
              "const": "boolean"
            },
            "default": {
              "title": "Default of the CSAF Extension Critical value",
              "description": "Contains the default of the critical value - either `true` or `false`.",
              "type": "string",
              "enum": [
                "false",
                "true"
              ]
            },
            "const": {
              "title": "Constant value of the CSAF Extension Critical value",
              "description": "Contains the only allowed value of the critical value as defined by the CSAF Extension Schema - either `true` or `false`.",
              "type": "boolean",
              "enum": [
                false,
                true
              ]
            }
          },
          "additionalProperties": false
        },
        "content": {
          "title": "CSAF Extension Content",
          "description": "Contains the definition of the object of the CSAF Extension content.",
          "type": "object",
          "$ref": "#/$defs/schema",
          "minProperties": 6,
          "required": [
            "title",
            "description",
            "type",
            "minProperties",
            "properties",
            "unevaluatedProperties"
          ],
          "properties": {
            "title": {
              "title": "Title of the CSAF Extension Content object",
              "description": "Contains the title for the CSAF Extension content.",
              "type": "string",
              "default": "Content",
              "minLength": 1
            },
            "description": {
              "title": "Description of the CSAF Extension Content object",
              "description": "Contains the description for the CSAF Extension content object.",
              "type": "string",
              "default": "Contains the additional information in its properties.",
              "minLength": 1
            },
            "type": {
              "title": "Type of the CSAF Extension Content object",
              "description": "Contains the type of the content object which is `object`.",
              "type": "string",
              "const": "object"
            },
            "minProperties": {
              "title": "Minimum count of properties of the CSAF Extension Content object",
              "description": "Contains the number of properties within the `object`.",
              "type": "integer",
              "minimum": 1,
              "multipleOf": 1
            },
            "unevaluatedProperties": {
              "title": "Unevaluated properties of the CSAF Extension Content object",
              "description": "Contains the fact that no properties can be unevaluated within the CSAF Extension Content object.",
              "type": "boolean",
              "const": false
            }
          },
          "additionalProperties": true
        }
      }
    },
    "additionalProperties": {
      "title": "CSAF Extension Schema Required Properties",
      "description": "Prohibits additional properties on this level.",
      "type": "boolean",
      "const": false
    }
  },
  "unevaluatedProperties": false
}

=== oasis-tcs/csaf/csaf_2.1/test/extension/data/valid/documentation-13/documentation-13-content_1.0.0.json
{
  "$schema": "https://docs.oasis-open.org/csaf/csaf/v2.1/schema/extension-metaschema.json",
  "$id": "https://raw.githubusercontent.com/oasis-tcs/csaf/refs/heads/master/csaf_2.1/extension/data/valid/documentation-13/documentation-13-content_1.0.0.json",
  "title": "CSAF Extension: Documentation 13",
  "description": "Representation of a valid extension for configurations used for documentation purposes.",
  "type": "object",
  "$defs": {
    "configuration_id_t": {
      "title": "Reference token for configuration instance",
      "description": "Token required to identify a configuration so that it can be referred to from other parts in the document. There is no predefined or required format for the configuration_id as long as it uniquely identifies a configuration in the context of the current document.",
      "type": "string",
      "minLength": 1,
      "examples": [
        "CSAFCID-0001",
        "CSAFCID-0002"
      ]
    },
    "configuration_t": {
      "title": "Configuration",
      "description": "Contains the description of a configuration and assigns it a configuration id.",
      "type": "object",
      "required": [
        "configuration_id",
        "details"
      ],
      "properties": {
        "configuration_id": {
          "$ref": "#/$defs/configuration_id_t"
        },
        "details": {
          "title": "Details of the Configuration",
          "description": "Contains all details as human-readable description on how to identify the configuration.",
          "type": "string",
          "minLength": 1
        }
      },
      "additionalProperties": false
    },
    "relationship_t": {
      "title": "Relationship",
      "description": "Establishes a link between an existing full_product_name_t element and a configuration, allowing the document producer to define a combination that form a new full_product_name entry.",
      "type": "object",
      "required": [
        "configuration_reference",
        "full_product_name",
        "product_reference"
      ],
      "properties": {
        "configuration_reference": {
          "title": "Configuration Reference",
          "description": "Holds a Configuration ID that refers to the Configuration element, which is referenced as the second element of the relationship.",
          "$ref": "#/$defs/configuration_id_t"
        },
        "full_product_name": {
          "$ref": "https://docs.oasis-open.org/csaf/csaf/v2.1/schema/csaf.json#/$defs/full_product_name_t"
        },
        "product_reference": {
          "title": "Product reference",
          "description": "Holds a Product ID that refers to the Full Product Name element, which is referenced as the first element of the relationship.",
          "$ref": "https://docs.oasis-open.org/csaf/csaf/v2.1/schema/csaf.json#/$defs/product_id_t"
        }
      },
      "additionalProperties": false
    }
  },
  "required": [
    "$schema",
    "category",
    "critical",
    "content"
  ],
  "properties": {
    "$schema": {
      "title": "CSAF Extension Schema",
      "description": "Contains the URL of the CSAF Extension JSON schema which the JSON object promises to be valid for.",
      "type": "string",
      "format": "uri",
      "const": "https://raw.githubusercontent.com/oasis-tcs/csaf/refs/heads/master/csaf_2.1/extension/data/valid/documentation-13/documentation-13-content_1.0.0.json"
    },
    "category": {
      "title": "Extension Category",
      "description": "Holds the category of the extension content.",
      "type": "string",
      "enum": [
        "essential",
        "significant",
        "supplementary"
      ]
    },
    "content": {
      "title": "Content",
      "description": "Contains the additional information in its properties.",
      "type": "object",
      "minProperties": 1,
      "properties": {
        "configuration_tree": {
          "title": "Configuration Tree",
          "description": "Contains configurations and their bindings to products.",
          "type": "object",
          "required": [
            "configurations",
            "relationships"
          ],
          "properties": {
            "configurations": {
              "title": "List of Configurations",
              "description": "Contains a list of configuration elements.",
              "type": "array",
              "minItems": 1,
              "uniqueItems": true,
              "items": {
                "$ref": "#/$defs/configuration_t"
              }
            },
            "relationships": {
              "title": "List of Relationships",
              "description": "Contains a list of product-configuration combinations.",
              "type": "array",
              "minItems": 1,
              "uniqueItems": true,
              "items": {
                "$ref": "#/$defs/relationship_t"
              }
            }
          }
        }
      },
      "unevaluatedProperties": false
    },
    "critical": {
      "title": "Critical",
      "description": "Determines whether using the extension would fail a mandatory test.",
      "type": "boolean",
      "const": true
    }
  },
  "additionalProperties": false
}

=== oasis-tcs/csaf/csaf_2.1/test/extension/data/valid/documentation-12/documentation-12-content_1.0.0.json
{
  "$schema": "https://docs.oasis-open.org/csaf/csaf/v2.1/schema/extension-metaschema.json",
  "$id": "https://raw.githubusercontent.com/oasis-tcs/csaf/refs/heads/master/csaf_2.1/extension/data/valid/documentation-12/documentation-12-content_1.0.0.json",
  "title": "CSAF Extension: Documentation 12",
  "description": "Representation of a valid extension used for documentation purposes.",
  "type": "object",
  "required": [
    "$schema",
    "category",
    "critical",
    "content"
  ],
  "properties": {
    "$schema": {
      "title": "CSAF Extension Schema",
      "description": "Contains the URL of the CSAF Extension JSON schema which the JSON object promises to be valid for.",
      "type": "string",
      "format": "uri",
      "const": "https://raw.githubusercontent.com/oasis-tcs/csaf/refs/heads/master/csaf_2.1/extension/data/valid/documentation-12/documentation-12-content_1.0.0.json"
    },
    "category": {
      "title": "Extension Category",
      "description": "Holds the category of the extension content.",
      "type": "string",
      "enum": [
        "essential",
        "significant",
        "supplementary"
      ]
    },
    "content": {
      "title": "Content",
      "description": "Contains the additional information in its properties.",
      "type": "object",
      "minProperties": 1,
      "required": [
        "documentation"
      ],
      "properties": {
        "documentation": {
          "title": "Documentation content",
          "description": "Contains a constant string to clarify that this is for documentation purposes only and not to be used in production.",
          "type": "string",
          "const": "This extension is for documentation and test purposed only. It is valid. It is not allowed to be used in a production CSAF."
        },
        "notes": {
          "title": "Notes",
          "description": "Contains a list of notes to convey a more complex structure.",
          "type": "array",
          "minItems": 1,
          "items": {
            "title": "Entry",
            "description": "Contains a single entry.",
            "type": "string",
            "minLength": 1
          }
        }
      },
      "unevaluatedProperties": false
    },
    "critical": {
      "title": "Critical",
      "description": "Determines whether using the extension would fail a mandatory test.",
      "type": "boolean",
      "const": false
    }
  },
  "additionalProperties": false
}
